#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
  Quit,
  MoveUp,
  MoveDown,
  MoveLeft,
  MoveRight,
  ToggleExpand,
  ScrollPreviewUp,
  ScrollPreviewDown,
  ToggleHidden,
  GoToTop,
  GoToBottom,
  SearchStart,
  SearchInput(char),
  SearchBackspace,
  SearchConfirm,
  SearchCancel,
  YankPath,
  OpenEditor,
  OpenClaude,
  OpenShell,
  ShrinkTree,
  GrowTree,
  GPress,
  Resize(u16, u16),
  Tick,
  None,
}
